# Generated by Django 5.2.1 on 2025-06-18 03:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.UUIDField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(default='Unknown', max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('totalCopies', models.IntegerField(default=0)),
                ('availabeCopies', models.IntegerField(default=0)),
                ('publicationdate', models.DateField(blank=True, null=True)),
                ('CoveimageUrl', models.URLField(blank=True, max_length=255, null=True)),
                ('Genre', models.CharField(choices=[('Fiction', 'Fiction'), ('NonFiction', 'NonFiction'), ('Science', 'Science'), ('History', 'History'), ('Biograpy', 'Biograpy')], default='Default', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HorseRace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horse_number', models.IntegerField()),
                ('horse_name', models.CharField(max_length=100)),
                ('odds_win', models.CharField(blank=True, max_length=20, null=True)),
                ('odds_place', models.CharField(blank=True, max_length=20, null=True)),
                ('race_date', models.DateField()),
                ('race_number', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('race_date', 'race_number', 'horse_number'), name='unique_horse_per_race')],
            },
        ),
        migrations.CreateModel(
            name='Quinella',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('race_date', models.DateField()),
                ('race_number', models.IntegerField()),
                ('horse_number_1', models.IntegerField()),
                ('horse_number_2', models.IntegerField()),
                ('odds', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('race_date', 'race_number', 'horse_number_1', 'horse_number_2'), name='unique_quinella_pair')],
            },
        ),
        migrations.CreateModel(
            name='QuinellaPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('race_date', models.DateField()),
                ('race_number', models.IntegerField()),
                ('horse_number_1', models.IntegerField()),
                ('horse_number_2', models.IntegerField()),
                ('odds', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('race_date', 'race_number', 'horse_number_1', 'horse_number_2'), name='unique_quinella_place_pair')],
            },
        ),
    ]
