# Generated by Django 5.2.1 on 2025-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('NonFiction', 'NonFiction'), ('Science', 'Science'), ('History', 'History'), ('Biograpy', 'Biograpy')], default='Default', max_length=255),
        ),
    ]
