# Generated by Django 5.2.1 on 2025-06-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('NonFiction', 'NonFiction'), ('Science', 'Science'), ('History', 'History'), ('Biograpy', 'Biograpy')], default='Default', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
