# Generated by Django 5.2.1 on 2025-06-19 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_book_genre_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuinellaOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quinella_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quinella_place_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('horse1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quinella_horse1', to='scraper.horse')),
                ('horse2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quinella_horse2', to='scraper.horse')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('racecourse', models.CharField(max_length=10)),
                ('race_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WinPlaceOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('place_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.race')),
            ],
            options={
                'unique_together': {('race', 'horse')},
            },
        ),
        migrations.DeleteModel(
            name='HorseRace',
        ),
        migrations.DeleteModel(
            name='Quinella',
        ),
        migrations.DeleteModel(
            name='QuinellaPlace',
        ),
        migrations.AddField(
            model_name='quinellaodds',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.race'),
        ),
        migrations.AlterUniqueTogether(
            name='quinellaodds',
            unique_together={('race', 'horse1', 'horse2')},
        ),
    ]
